# 系统名称
spring:
  application:
    name: hengboy-spring-boot-actuator

# 管理节点配置
management:
  endpoints:
    web:
      # actuator的前缀地址
      base-path: /
  # 显示详细健康信息
  endpoint:
    health:
      show-details: always